### ISSUE TITLE
Translation from WordPress.org

### ISSUE THREAD

**Issue by reuhno** [pressidium/pressidium-cookie-consent#131]
Hello,

I've recently spent over 2 hours translating your plugin into French (82% done – 332 out of 398 strings). I generated and uploaded the .po, .mo, .json, and relevant PHP files to my WordPress installation. However, I noticed that only the PHP-based strings are being translated.

All the JavaScript-based strings remain in English, which is quite frustrating, especially after dedicating time to what I thought would be a complete translation. It seems that your plugin uses many strings in JavaScript that are not properly localized or loaded for translation via standard WordPress methods (e.g., wp_set_script_translations).

Could you please confirm if JavaScript localization is properly implemented in the plugin? If not, would you consider adding support for it in a future release?

This plugin has great potential, and it would be fantastic to see it fully translatable.

Thank you!

Best regards,
Renaud

**Comment by over-engineer** [comment]
Hey, @reuhno!

Greateful for your contribution to the French translation and for pointing out that issue!

You’re spot on—we totally missed [`wp_set_script_translations()`](https://developer.wordpress.org/reference/functions/wp_set_script_translations/).

It’ll likely be fixed in the next release.

**Comment by reuhno** [comment]
Ah, great, thanks for the follow-up. Do you have any idea when this update will be released?

**Comment by over-engineer** [comment]
>Do you have any idea when this update will be released?

@reuhno Most likely early next week.

**Comment by over-engineer** [comment]
This was addressed in `1.8.0`, which was just released on the WordPress Plugin Directory. Closing as resolved.

**Comment by reuhno** [comment]
Thanks for you @over-engineer for your relase. Sadly it doesn't fix!

I've made some research and I think I found what's going on.

In the `include/Plugin.php` file, here are some suggestions : 

**Line 79:** 
replace
`dirname( plugin_basename( __FILE__ ) ) . '/languages'`
by
` dirname( Pressidium\WP\CookieConsent\PLUGIN_DIR) . '/languages'`

**Line 89:**
replace
 `add_action( 'init', array( $this, 'load_textdomain' ) );`
by
  `add_action( 'plugins_loaded', array( $this, 'load_textdomain' ) );`

(This allows you to remove the WordPress load text loading warning that was introduced in recent versions)

With theses edit, it's seems ok on my side.

**Comment by over-engineer** [comment]
@reuhno Ah, yes, you’re right, the path to the `languages` directory is incorrect. I was testing it using files in `/wp-content/languages/plugins/` rather than `/wp-content/plugins/pressidium-cookie-consent/languages/`.

I’ll get this fixed in the next update. That said, it shouldn’t affect translations pulled from WordPress.org. I believe French will be automatically downloaded once it hits the 90% threshold.

Until the fix is released, as a temporary workaround, placing the files (`.po`, `.mo`, and `.json`) under `/wp-content/languages/plugins/` should work if that’s an option for you.

**Comment by reuhno** [comment]
> Ah, yes, you’re right, the path to the `languages` directory is incorrect.

Indeed

>  I was testing it using files in `/wp-content/languages/plugins/` rather than `/wp-content/plugins/pressidium-cookie-consent/languages/`.
> Until the fix is released, as a temporary workaround, placing the files (.po, .mo, and .json) under /wp-content/languages/plugins/ should work if that’s an option for you.

No, actually not, because your `dirname( plugin_basename( __FILE__ ) ) . '/languages'` directive is related to `/wp-content/plugins/pressidium-cookie-consent/Plugin/languages/` folder.

> Until the fix is released, as a temporary workaround, placing the files (.po, .mo, and .json) under /wp-content/languages/plugins/ should work if that’s an option for you.

With my [suggestion yesterday](https://github.com/pressidium/pressidium-cookie-consent/issues/131#issuecomment-2851333762), I made tests with `languages/plugins/pressidium-cookie-consent-fr_FR.po` and it works well

In order to force downloading of language packages from the repo, I used this plugin 
: [https://fr.wordpress.org/plugins/translation-tools/](https://fr.wordpress.org/plugins/translation-tools/)

Everything's work fine (but only with my dirname rename ;) )

**Comment by over-engineer** [comment]
>No, actually not, because your `dirname( plugin_basename( __FILE__ ) ) . '/languages'` directive is related to `/wp-content/plugins/pressidium-cookie-consent/Plugin/languages/` folder.

@reuhno From what I understand, WordPress looks into multiple locations for translation files. Even if a plugin sets an incorrect custom path via [`load_plugin_textdomain()`](https://developer.wordpress.org/reference/functions/load_plugin_textdomain/), WordPress will still load `.mo`/`.po` files from `/wp-content/languages/plugins/` if they are available there.

I confirmed that by placing the following translation files:

* `pressidium-cookie-consent-fr_FR-417bdfa8356677737e61273afe693292.json`
* `pressidium-cookie-consent-fr_FR-a712815693aeed5862e61896b99321fc.json`
* `pressidium-cookie-consent-fr_FR.l10n.php`
* `pressidium-cookie-consent-fr_FR.mo`
* `pressidium-cookie-consent-fr_FR.po`

under `/wp-content/languages/plugins/` on a WordPress site running Pressidium Cookie Consent version `1.8.0`, and the French translation was picked up as expected.

![Image](https://github.com/user-attachments/assets/27a08b84-e295-47a4-8511-d5314f95681b)

![Image](https://github.com/user-attachments/assets/716fdf05-08ae-4b6a-a6d0-717bd3e60fb0)

![Image](https://github.com/user-attachments/assets/6e749f62-cfd3-4028-a66d-eea2afadebce)

Furthermore, `load_plugin_textdomain()` can be **completely omitted** for plugins hosted on WordPress.org — WordPress will automatically load any translations.

In the next version, I’ll likely fix the path to the `languages/` directory or just drop the `load_plugin_textdomain()` call altogether.

https://github.com/pressidium/pressidium-cookie-consent/blob/f355c0095b710c9ab877cd5406c775fa665ef253/includes/Plugin.php#L70-L81

>**Line 89:**
>replace
>`add_action( 'init', array( $this, 'load_textdomain' ) );`
>by
>`add_action( 'plugins_loaded', array( $this, 'load_textdomain' ) );`
>
>(This allows you to remove the WordPress load text loading warning that was introduced in recent versions)

Can you clarify which warning you’re referring to? As far as I know, WordPress warns developers if they are loading translations **too early** in a plugin.

For example, there’s this `_doing_it_wrong()` warning:

```
PHP Notice: Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>my-plugin</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later.
```

where it’s made clear that translations must not be loaded before the `init` hook.

https://github.com/pressidium/pressidium-cookie-consent/blob/f355c0095b710c9ab877cd5406c775fa665ef253/includes/Plugin.php#L89

The suggested [`plugins_loaded`](https://developer.wordpress.org/reference/hooks/plugins_loaded/) hook **fires prior** to [`init`](https://developer.wordpress.org/reference/hooks/init/), the hook in use at the moment.

[WordPress docs contain examples](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain) that hook into `init` to call `load_plugin_textdomain()`. Additionally, the [Internationalization improvements in 6.7](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/) post notes, under the “Warnings if translations are loaded too early”:

>**Reminder:** If your plugin or theme is hosted on WordPress.org and is still using `load_*_textdomain()`, **you can remove this call**. […] move the function call to a later hook such as `init`.

and

>When attempting to load translations before `after_setup_theme` or `init`, WordPress tries to load the current user earlier than usual, without giving other plugins a chance to potentially hook into the process. It also prevents any plugins from filtering translation calls, e.g. for switching the locale or file location. Hence the addition of this warning to call out this unexpected behavior.

Unless I’ve overlooked something (which I might have), the `init` action seems to be the right place to hook into for calling `load_plugin_textdomain()`.

References
---

* [How to Internationalize Your Plugin](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/)
* [Internationalization improvements in 6.7](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/)
* [`WP_Textdomain_Registry`](https://developer.wordpress.org/reference/classes/wp_textdomain_registry/)
* [`load_plugin_textdomain()`](https://developer.wordpress.org/reference/functions/load_plugin_textdomain/)
* [Notice: Function _load_textdomain_just_in_time was called incorrectly](https://stackoverflow.com/questions/79198701/notice-function-load-textdomain-just-in-time-was-called-incorrectly)

**Comment by reuhno** [comment]
First of all, thank you for taking this seriously and looking into it in depth. I really appreciate that.

I believe I indeed made some mistakes. My initial observation was that, despite the latest release and placing the language files in wp-content/languages/plugins, it still wasn’t working.

I made several modifications to your plugin to debug and look for a solution. At one point, I encountered the same error you described:

PHP Notice: Function _load_textdomain_just_in_time was called incorrectly.

I applied some adjustments, including those I suggested to you, and that seemed to solve the problem. However, it's likely that the issue was caused by external factors, as I was testing many things at once.

I did this quite quickly and without a proper method,

The WordPress documentation makes sense, and I trust your implementation.

I’m sorry if my earlier response was misleading or incorrect.

Today, I was able to calmly retest everything. Indeed, after downloading all the language files (PO, MO, PHP, and JSON) into wp-content/languages/plugins, everything now works as expected.

The path in load_textdomain() does need to be fixed, but not necessarily the way I did it, because the Pressidium\WP\CookieConsent\PLUGIN_DIR constant isn’t yet available at the init hook (which is why I had to load it earlier using plugins_loaded). As you pointed out, this doesn’t seem to matter in practice—I drew the wrong conclusions from my earlier tests.

Everything's fine for me now, all I need to do is adjust the few strings to reach 90% translations and trigger an automatic package on the repo and we'll be good to go.

Thanks again for everything and sorry if in my attempt to fix real problems, there were real mistakes on my part.

**Comment by over-engineer** [comment]
@reuhno No worries at all! Thank _you_ for taking the time to dive in, help translate the plugin to French, and report the JavaScript i18n issue.

Debugging these things is rarely straightforward, especially when several moving parts are invloved. Honestly, small hiccups are totally fine, it’s all part of the process—your input was super helpful.

I genuinely appreciate all the time you’ve put into this 🙂

**Comment by reuhno** [comment]
Thanks ;)

I close this ticket if it's fine.
(90% done ;) )
